services:
  web:
    build: .
    command:  python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db


  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin_reception
      POSTGRES_PASSWORD: asert2209
      POSTGRES_DB: db_reception
    ports:
      - "5432:5432"