# Generated by Django 5.1.6 on 2025-02-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
